easy_admin:
    # ...
    design:
        templates:
            layout: 'admin/dashboard.html.twig'
        menu:
            - { entity: 'User' }
    entities:
        YourEntity:
            class: App\Entity\User
            # ...
            list:
                actions:
                    - { name: 'export', type: 'route', icon: 'fa-file-excel', label: 'Export to Excel', route: 'admin_custom_export' }
